//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestService.BankingDepartment {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BankingDepartment.IBankingDepartment")]
    public interface IBankingDepartment {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IBankingDepartment/message")]
        void message([System.ServiceModel.MessageParameterAttribute(Name="message")] string message1);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IBankingDepartment/message")]
        System.Threading.Tasks.Task messageAsync(string message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IBankingDepartment/newOrder")]
        void newOrder(Models.Order order);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IBankingDepartment/newOrder")]
        System.Threading.Tasks.Task newOrderAsync(Models.Order order);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBankingDepartmentChannel : IBankingDepartment, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BankingDepartmentClient : System.ServiceModel.ClientBase<IBankingDepartment>, IBankingDepartment {
        
        public BankingDepartmentClient() {
        }
        
        public BankingDepartmentClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BankingDepartmentClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BankingDepartmentClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BankingDepartmentClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void message(string message1) {
            base.Channel.message(message1);
        }
        
        public System.Threading.Tasks.Task messageAsync(string message) {
            return base.Channel.messageAsync(message);
        }
        
        public void newOrder(Models.Order order) {
            base.Channel.newOrder(order);
        }
        
        public System.Threading.Tasks.Task newOrderAsync(Models.Order order) {
            return base.Channel.newOrderAsync(order);
        }
    }
}
